# Generated by Django 3.1.7 on 2021-03-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20210310_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
